<?php
/**
 * PaymentLinkResponse
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  FinversePhp
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Finverse Public
 *
 * Documentation of the early finverse services
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@finverse.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace FinversePhp\Model;

use \ArrayAccess;
use \FinversePhp\ObjectSerializer;

/**
 * PaymentLinkResponse Class Doc Comment
 *
 * @category Class
 * @package  FinversePhp
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PaymentLinkResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PaymentLinkResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'payment_link_id' => 'string',
        'amount' => 'int',
        'currency' => 'string',
        'link_customizations' => '\FinversePhp\Model\PaymentLinkCustomizations',
        'mode' => 'string',
        'payment_details' => '\FinversePhp\Model\PaymentLinkDetails',
        'unique_reference_id' => 'string',
        'payment_setup_options' => '\FinversePhp\Model\PaymentSetupOptions',
        'metadata' => 'array<string,string>',
        'payment_metadata' => 'array<string,string>',
        'url' => 'string',
        'status' => 'string',
        'session_status' => 'string',
        'expires_at' => '\DateTime',
        'created_at' => '\DateTime',
        'updated_at' => '\DateTime',
        'payment' => '\FinversePhp\Model\PaymentResponse',
        'sender' => '\FinversePhp\Model\PaymentLinkSenderResponse',
        'payment_method' => '\FinversePhp\Model\PaymentMethodResponse',
        'integration_metadata' => '\FinversePhp\Model\IntegrationMetadataResponse'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'payment_link_id' => null,
        'amount' => null,
        'currency' => null,
        'link_customizations' => null,
        'mode' => null,
        'payment_details' => null,
        'unique_reference_id' => null,
        'payment_setup_options' => null,
        'metadata' => null,
        'payment_metadata' => null,
        'url' => null,
        'status' => null,
        'session_status' => null,
        'expires_at' => 'date-time',
        'created_at' => 'date-time',
        'updated_at' => 'date-time',
        'payment' => null,
        'sender' => null,
        'payment_method' => null,
        'integration_metadata' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'payment_link_id' => false,
        'amount' => false,
        'currency' => false,
        'link_customizations' => false,
        'mode' => false,
        'payment_details' => false,
        'unique_reference_id' => false,
        'payment_setup_options' => false,
        'metadata' => false,
        'payment_metadata' => false,
        'url' => false,
        'status' => false,
        'session_status' => false,
        'expires_at' => false,
        'created_at' => false,
        'updated_at' => false,
        'payment' => false,
        'sender' => false,
        'payment_method' => false,
        'integration_metadata' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'payment_link_id' => 'payment_link_id',
        'amount' => 'amount',
        'currency' => 'currency',
        'link_customizations' => 'link_customizations',
        'mode' => 'mode',
        'payment_details' => 'payment_details',
        'unique_reference_id' => 'unique_reference_id',
        'payment_setup_options' => 'payment_setup_options',
        'metadata' => 'metadata',
        'payment_metadata' => 'payment_metadata',
        'url' => 'url',
        'status' => 'status',
        'session_status' => 'session_status',
        'expires_at' => 'expires_at',
        'created_at' => 'created_at',
        'updated_at' => 'updated_at',
        'payment' => 'payment',
        'sender' => 'sender',
        'payment_method' => 'payment_method',
        'integration_metadata' => 'integration_metadata'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'payment_link_id' => 'setPaymentLinkId',
        'amount' => 'setAmount',
        'currency' => 'setCurrency',
        'link_customizations' => 'setLinkCustomizations',
        'mode' => 'setMode',
        'payment_details' => 'setPaymentDetails',
        'unique_reference_id' => 'setUniqueReferenceId',
        'payment_setup_options' => 'setPaymentSetupOptions',
        'metadata' => 'setMetadata',
        'payment_metadata' => 'setPaymentMetadata',
        'url' => 'setUrl',
        'status' => 'setStatus',
        'session_status' => 'setSessionStatus',
        'expires_at' => 'setExpiresAt',
        'created_at' => 'setCreatedAt',
        'updated_at' => 'setUpdatedAt',
        'payment' => 'setPayment',
        'sender' => 'setSender',
        'payment_method' => 'setPaymentMethod',
        'integration_metadata' => 'setIntegrationMetadata'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'payment_link_id' => 'getPaymentLinkId',
        'amount' => 'getAmount',
        'currency' => 'getCurrency',
        'link_customizations' => 'getLinkCustomizations',
        'mode' => 'getMode',
        'payment_details' => 'getPaymentDetails',
        'unique_reference_id' => 'getUniqueReferenceId',
        'payment_setup_options' => 'getPaymentSetupOptions',
        'metadata' => 'getMetadata',
        'payment_metadata' => 'getPaymentMetadata',
        'url' => 'getUrl',
        'status' => 'getStatus',
        'session_status' => 'getSessionStatus',
        'expires_at' => 'getExpiresAt',
        'created_at' => 'getCreatedAt',
        'updated_at' => 'getUpdatedAt',
        'payment' => 'getPayment',
        'sender' => 'getSender',
        'payment_method' => 'getPaymentMethod',
        'integration_metadata' => 'getIntegrationMetadata'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const MODE_PAYMENT = 'PAYMENT';
    public const STATUS_CREATED = 'CREATED';
    public const STATUS_PAID = 'PAID';
    public const STATUS_EXPIRED = 'EXPIRED';
    public const SESSION_STATUS_OPEN = 'OPEN';
    public const SESSION_STATUS_PROCESSING = 'PROCESSING';
    public const SESSION_STATUS_COMPLETE = 'COMPLETE';
    public const SESSION_STATUS_FAILED = 'FAILED';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getModeAllowableValues()
    {
        return [
            self::MODE_PAYMENT,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_CREATED,
            self::STATUS_PAID,
            self::STATUS_EXPIRED,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSessionStatusAllowableValues()
    {
        return [
            self::SESSION_STATUS_OPEN,
            self::SESSION_STATUS_PROCESSING,
            self::SESSION_STATUS_COMPLETE,
            self::SESSION_STATUS_FAILED,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('payment_link_id', $data ?? [], null);
        $this->setIfExists('amount', $data ?? [], null);
        $this->setIfExists('currency', $data ?? [], null);
        $this->setIfExists('link_customizations', $data ?? [], null);
        $this->setIfExists('mode', $data ?? [], null);
        $this->setIfExists('payment_details', $data ?? [], null);
        $this->setIfExists('unique_reference_id', $data ?? [], null);
        $this->setIfExists('payment_setup_options', $data ?? [], null);
        $this->setIfExists('metadata', $data ?? [], null);
        $this->setIfExists('payment_metadata', $data ?? [], null);
        $this->setIfExists('url', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('session_status', $data ?? [], null);
        $this->setIfExists('expires_at', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('updated_at', $data ?? [], null);
        $this->setIfExists('payment', $data ?? [], null);
        $this->setIfExists('sender', $data ?? [], null);
        $this->setIfExists('payment_method', $data ?? [], null);
        $this->setIfExists('integration_metadata', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getModeAllowableValues();
        if (!is_null($this->container['mode']) && !in_array($this->container['mode'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'mode', must be one of '%s'",
                $this->container['mode'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['unique_reference_id']) && (mb_strlen($this->container['unique_reference_id']) < 1)) {
            $invalidProperties[] = "invalid value for 'unique_reference_id', the character length must be bigger than or equal to 1.";
        }

        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getSessionStatusAllowableValues();
        if (!is_null($this->container['session_status']) && !in_array($this->container['session_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'session_status', must be one of '%s'",
                $this->container['session_status'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets payment_link_id
     *
     * @return string|null
     */
    public function getPaymentLinkId()
    {
        return $this->container['payment_link_id'];
    }

    /**
     * Sets payment_link_id
     *
     * @param string|null $payment_link_id Finverse Payment Link ID
     *
     * @return self
     */
    public function setPaymentLinkId($payment_link_id)
    {
        if (is_null($payment_link_id)) {
            throw new \InvalidArgumentException('non-nullable payment_link_id cannot be null');
        }
        $this->container['payment_link_id'] = $payment_link_id;

        return $this;
    }

    /**
     * Gets amount
     *
     * @return int|null
     */
    public function getAmount()
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param int|null $amount The amount of the payment. Expressed in currency's smallest unit or “minor unit”, as defined in ISO 4217.
     *
     * @return self
     */
    public function setAmount($amount)
    {
        if (is_null($amount)) {
            throw new \InvalidArgumentException('non-nullable amount cannot be null');
        }
        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets currency
     *
     * @return string|null
     */
    public function getCurrency()
    {
        return $this->container['currency'];
    }

    /**
     * Sets currency
     *
     * @param string|null $currency currency
     *
     * @return self
     */
    public function setCurrency($currency)
    {
        if (is_null($currency)) {
            throw new \InvalidArgumentException('non-nullable currency cannot be null');
        }
        $this->container['currency'] = $currency;

        return $this;
    }

    /**
     * Gets link_customizations
     *
     * @return \FinversePhp\Model\PaymentLinkCustomizations|null
     */
    public function getLinkCustomizations()
    {
        return $this->container['link_customizations'];
    }

    /**
     * Sets link_customizations
     *
     * @param \FinversePhp\Model\PaymentLinkCustomizations|null $link_customizations link_customizations
     *
     * @return self
     */
    public function setLinkCustomizations($link_customizations)
    {
        if (is_null($link_customizations)) {
            throw new \InvalidArgumentException('non-nullable link_customizations cannot be null');
        }
        $this->container['link_customizations'] = $link_customizations;

        return $this;
    }

    /**
     * Gets mode
     *
     * @return string|null
     */
    public function getMode()
    {
        return $this->container['mode'];
    }

    /**
     * Sets mode
     *
     * @param string|null $mode The payment link mode
     *
     * @return self
     */
    public function setMode($mode)
    {
        if (is_null($mode)) {
            throw new \InvalidArgumentException('non-nullable mode cannot be null');
        }
        $allowedValues = $this->getModeAllowableValues();
        if (!in_array($mode, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'mode', must be one of '%s'",
                    $mode,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['mode'] = $mode;

        return $this;
    }

    /**
     * Gets payment_details
     *
     * @return \FinversePhp\Model\PaymentLinkDetails|null
     */
    public function getPaymentDetails()
    {
        return $this->container['payment_details'];
    }

    /**
     * Sets payment_details
     *
     * @param \FinversePhp\Model\PaymentLinkDetails|null $payment_details payment_details
     *
     * @return self
     */
    public function setPaymentDetails($payment_details)
    {
        if (is_null($payment_details)) {
            throw new \InvalidArgumentException('non-nullable payment_details cannot be null');
        }
        $this->container['payment_details'] = $payment_details;

        return $this;
    }

    /**
     * Gets unique_reference_id
     *
     * @return string|null
     */
    public function getUniqueReferenceId()
    {
        return $this->container['unique_reference_id'];
    }

    /**
     * Sets unique_reference_id
     *
     * @param string|null $unique_reference_id Unique reference id to identifying the payment to be collected.
     *
     * @return self
     */
    public function setUniqueReferenceId($unique_reference_id)
    {
        if (is_null($unique_reference_id)) {
            throw new \InvalidArgumentException('non-nullable unique_reference_id cannot be null');
        }

        if ((mb_strlen($unique_reference_id) < 1)) {
            throw new \InvalidArgumentException('invalid length for $unique_reference_id when calling PaymentLinkResponse., must be bigger than or equal to 1.');
        }

        $this->container['unique_reference_id'] = $unique_reference_id;

        return $this;
    }

    /**
     * Gets payment_setup_options
     *
     * @return \FinversePhp\Model\PaymentSetupOptions|null
     */
    public function getPaymentSetupOptions()
    {
        return $this->container['payment_setup_options'];
    }

    /**
     * Sets payment_setup_options
     *
     * @param \FinversePhp\Model\PaymentSetupOptions|null $payment_setup_options payment_setup_options
     *
     * @return self
     */
    public function setPaymentSetupOptions($payment_setup_options)
    {
        if (is_null($payment_setup_options)) {
            throw new \InvalidArgumentException('non-nullable payment_setup_options cannot be null');
        }
        $this->container['payment_setup_options'] = $payment_setup_options;

        return $this;
    }

    /**
     * Gets metadata
     *
     * @return array<string,string>|null
     */
    public function getMetadata()
    {
        return $this->container['metadata'];
    }

    /**
     * Sets metadata
     *
     * @param array<string,string>|null $metadata Additional attributes of the payment link in key:value format (e.g. payment_id: 1234). It supports up to 10 key:value pairs, whereas the key and value supports up to 50 and 1000 characters respectively.
     *
     * @return self
     */
    public function setMetadata($metadata)
    {
        if (is_null($metadata)) {
            throw new \InvalidArgumentException('non-nullable metadata cannot be null');
        }
        $this->container['metadata'] = $metadata;

        return $this;
    }

    /**
     * Gets payment_metadata
     *
     * @return array<string,string>|null
     */
    public function getPaymentMetadata()
    {
        return $this->container['payment_metadata'];
    }

    /**
     * Sets payment_metadata
     *
     * @param array<string,string>|null $payment_metadata Key-Value metadata to store on payments created on this Payment Link
     *
     * @return self
     */
    public function setPaymentMetadata($payment_metadata)
    {
        if (is_null($payment_metadata)) {
            throw new \InvalidArgumentException('non-nullable payment_metadata cannot be null');
        }
        $this->container['payment_metadata'] = $payment_metadata;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string|null
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string|null $url The URL for payment link
     *
     * @return self
     */
    public function setUrl($url)
    {
        if (is_null($url)) {
            throw new \InvalidArgumentException('non-nullable url cannot be null');
        }
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status The status of payment link
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'status', must be one of '%s'",
                    $status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets session_status
     *
     * @return string|null
     */
    public function getSessionStatus()
    {
        return $this->container['session_status'];
    }

    /**
     * Sets session_status
     *
     * @param string|null $session_status The session status of payment link
     *
     * @return self
     */
    public function setSessionStatus($session_status)
    {
        if (is_null($session_status)) {
            throw new \InvalidArgumentException('non-nullable session_status cannot be null');
        }
        $allowedValues = $this->getSessionStatusAllowableValues();
        if (!in_array($session_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'session_status', must be one of '%s'",
                    $session_status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['session_status'] = $session_status;

        return $this;
    }

    /**
     * Gets expires_at
     *
     * @return \DateTime|null
     */
    public function getExpiresAt()
    {
        return $this->container['expires_at'];
    }

    /**
     * Sets expires_at
     *
     * @param \DateTime|null $expires_at Timestamp of when the payment link was or will expired in ISO format (YYYY-MM-DDTHH:MM:SS.SSSZ)
     *
     * @return self
     */
    public function setExpiresAt($expires_at)
    {
        if (is_null($expires_at)) {
            throw new \InvalidArgumentException('non-nullable expires_at cannot be null');
        }
        $this->container['expires_at'] = $expires_at;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime|null
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime|null $created_at Timestamp of when the payment link was created in ISO format (YYYY-MM-DDTHH:MM:SS.SSSZ)
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime|null
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime|null $updated_at Timestamp of when the payment link was last updated in ISO format (YYYY-MM-DDTHH:MM:SS.SSSZ)
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        if (is_null($updated_at)) {
            throw new \InvalidArgumentException('non-nullable updated_at cannot be null');
        }
        $this->container['updated_at'] = $updated_at;

        return $this;
    }

    /**
     * Gets payment
     *
     * @return \FinversePhp\Model\PaymentResponse|null
     */
    public function getPayment()
    {
        return $this->container['payment'];
    }

    /**
     * Sets payment
     *
     * @param \FinversePhp\Model\PaymentResponse|null $payment payment
     *
     * @return self
     */
    public function setPayment($payment)
    {
        if (is_null($payment)) {
            throw new \InvalidArgumentException('non-nullable payment cannot be null');
        }
        $this->container['payment'] = $payment;

        return $this;
    }

    /**
     * Gets sender
     *
     * @return \FinversePhp\Model\PaymentLinkSenderResponse|null
     */
    public function getSender()
    {
        return $this->container['sender'];
    }

    /**
     * Sets sender
     *
     * @param \FinversePhp\Model\PaymentLinkSenderResponse|null $sender sender
     *
     * @return self
     */
    public function setSender($sender)
    {
        if (is_null($sender)) {
            throw new \InvalidArgumentException('non-nullable sender cannot be null');
        }
        $this->container['sender'] = $sender;

        return $this;
    }

    /**
     * Gets payment_method
     *
     * @return \FinversePhp\Model\PaymentMethodResponse|null
     */
    public function getPaymentMethod()
    {
        return $this->container['payment_method'];
    }

    /**
     * Sets payment_method
     *
     * @param \FinversePhp\Model\PaymentMethodResponse|null $payment_method payment_method
     *
     * @return self
     */
    public function setPaymentMethod($payment_method)
    {
        if (is_null($payment_method)) {
            throw new \InvalidArgumentException('non-nullable payment_method cannot be null');
        }
        $this->container['payment_method'] = $payment_method;

        return $this;
    }

    /**
     * Gets integration_metadata
     *
     * @return \FinversePhp\Model\IntegrationMetadataResponse|null
     */
    public function getIntegrationMetadata()
    {
        return $this->container['integration_metadata'];
    }

    /**
     * Sets integration_metadata
     *
     * @param \FinversePhp\Model\IntegrationMetadataResponse|null $integration_metadata integration_metadata
     *
     * @return self
     */
    public function setIntegrationMetadata($integration_metadata)
    {
        if (is_null($integration_metadata)) {
            throw new \InvalidArgumentException('non-nullable integration_metadata cannot be null');
        }
        $this->container['integration_metadata'] = $integration_metadata;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


