<?php
/**
 * RapidstorMetadataRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  FinversePhp
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Finverse Public
 *
 * Documentation of the early finverse services
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@finverse.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace FinversePhp\Model;

use \ArrayAccess;
use \FinversePhp\ObjectSerializer;

/**
 * RapidstorMetadataRequest Class Doc Comment
 *
 * @category Class
 * @package  FinversePhp
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RapidstorMetadataRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'RapidstorMetadataRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'corp_code' => 'string',
        's_location_code' => 'string',
        'tenant_id' => 'string',
        'i_anniv_days' => 'float',
        'account_token' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'corp_code' => null,
        's_location_code' => null,
        'tenant_id' => null,
        'i_anniv_days' => 'int32',
        'account_token' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'corp_code' => false,
        's_location_code' => false,
        'tenant_id' => false,
        'i_anniv_days' => false,
        'account_token' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'corp_code' => 'corp_code',
        's_location_code' => 's_location_code',
        'tenant_id' => 'tenant_id',
        'i_anniv_days' => 'i_anniv_days',
        'account_token' => 'account_token'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'corp_code' => 'setCorpCode',
        's_location_code' => 'setSLocationCode',
        'tenant_id' => 'setTenantId',
        'i_anniv_days' => 'setIAnnivDays',
        'account_token' => 'setAccountToken'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'corp_code' => 'getCorpCode',
        's_location_code' => 'getSLocationCode',
        'tenant_id' => 'getTenantId',
        'i_anniv_days' => 'getIAnnivDays',
        'account_token' => 'getAccountToken'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('corp_code', $data ?? [], null);
        $this->setIfExists('s_location_code', $data ?? [], null);
        $this->setIfExists('tenant_id', $data ?? [], null);
        $this->setIfExists('i_anniv_days', $data ?? [], null);
        $this->setIfExists('account_token', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['corp_code'] === null) {
            $invalidProperties[] = "'corp_code' can't be null";
        }
        if ($this->container['s_location_code'] === null) {
            $invalidProperties[] = "'s_location_code' can't be null";
        }
        if ($this->container['tenant_id'] === null) {
            $invalidProperties[] = "'tenant_id' can't be null";
        }
        if (!is_null($this->container['i_anniv_days']) && ($this->container['i_anniv_days'] > 31)) {
            $invalidProperties[] = "invalid value for 'i_anniv_days', must be smaller than or equal to 31.";
        }

        if (!is_null($this->container['i_anniv_days']) && ($this->container['i_anniv_days'] < 1)) {
            $invalidProperties[] = "invalid value for 'i_anniv_days', must be bigger than or equal to 1.";
        }

        if ($this->container['account_token'] === null) {
            $invalidProperties[] = "'account_token' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets corp_code
     *
     * @return string
     */
    public function getCorpCode()
    {
        return $this->container['corp_code'];
    }

    /**
     * Sets corp_code
     *
     * @param string $corp_code corp_code
     *
     * @return self
     */
    public function setCorpCode($corp_code)
    {
        if (is_null($corp_code)) {
            throw new \InvalidArgumentException('non-nullable corp_code cannot be null');
        }
        $this->container['corp_code'] = $corp_code;

        return $this;
    }

    /**
     * Gets s_location_code
     *
     * @return string
     */
    public function getSLocationCode()
    {
        return $this->container['s_location_code'];
    }

    /**
     * Sets s_location_code
     *
     * @param string $s_location_code s_location_code
     *
     * @return self
     */
    public function setSLocationCode($s_location_code)
    {
        if (is_null($s_location_code)) {
            throw new \InvalidArgumentException('non-nullable s_location_code cannot be null');
        }
        $this->container['s_location_code'] = $s_location_code;

        return $this;
    }

    /**
     * Gets tenant_id
     *
     * @return string
     */
    public function getTenantId()
    {
        return $this->container['tenant_id'];
    }

    /**
     * Sets tenant_id
     *
     * @param string $tenant_id tenant_id
     *
     * @return self
     */
    public function setTenantId($tenant_id)
    {
        if (is_null($tenant_id)) {
            throw new \InvalidArgumentException('non-nullable tenant_id cannot be null');
        }
        $this->container['tenant_id'] = $tenant_id;

        return $this;
    }

    /**
     * Gets i_anniv_days
     *
     * @return float|null
     */
    public function getIAnnivDays()
    {
        return $this->container['i_anniv_days'];
    }

    /**
     * Sets i_anniv_days
     *
     * @param float|null $i_anniv_days i_anniv_days
     *
     * @return self
     */
    public function setIAnnivDays($i_anniv_days)
    {
        if (is_null($i_anniv_days)) {
            throw new \InvalidArgumentException('non-nullable i_anniv_days cannot be null');
        }

        if (($i_anniv_days > 31)) {
            throw new \InvalidArgumentException('invalid value for $i_anniv_days when calling RapidstorMetadataRequest., must be smaller than or equal to 31.');
        }
        if (($i_anniv_days < 1)) {
            throw new \InvalidArgumentException('invalid value for $i_anniv_days when calling RapidstorMetadataRequest., must be bigger than or equal to 1.');
        }

        $this->container['i_anniv_days'] = $i_anniv_days;

        return $this;
    }

    /**
     * Gets account_token
     *
     * @return string
     */
    public function getAccountToken()
    {
        return $this->container['account_token'];
    }

    /**
     * Sets account_token
     *
     * @param string $account_token account_token
     *
     * @return self
     */
    public function setAccountToken($account_token)
    {
        if (is_null($account_token)) {
            throw new \InvalidArgumentException('non-nullable account_token cannot be null');
        }
        $this->container['account_token'] = $account_token;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


